name: CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: 'rmm-fl/App'
          ref: 'i-26607'

      - name: Setup Node.js
        shell: bash
        run: nvm install && nvm use

      - name: Install npm dependencies
        shell: bash
        run: npm ci

      - name: Build ios
        shell: bash
        run: npm run ios-build

      - name: List file tree
        shell: bash
        run: tree -fi
